
services:
  postgres:
    image: postgres:15-alpine
    container_name: store-db
    environment:
      POSTGRES_DB: dbstore
      POSTGRES_USER: store
      POSTGRES_PASSWORD: Store25
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - store-network
    #restart: unless-stopped

volumes:
  postgres_data:

networks:
  store-network:
    driver: bridge